
version: 2

sources:
    - name: staging
      #For bigquery:
      database: zoomcamp-340819
      schema: football_data_staging
      # loaded_at_field: record_loaded_at
      tables:
        - name: transfers

models:
  - name: players_retired
    description: "List of players retired"
    columns:
      - name: player_name
        description: "The player name"
        tests:
          - unique
          - not_null
      - name: last_club
        description: "Last club where player played before retirenment"
      - name: league
        description: "League where player finish his career"
      - name: year
        description: "Year of retirenment"
  - name: club_max_transfers_by_year
    description: "Clubs that more money spent in transfers by year"
    columns:
      - name: year
        description: "Year"
        tests:
          - unique
          - not_null
      - name: club
        description: "Club that spent more money that year"
      - name: total
        description: "Total in millions of pounds (£)"

